### ISSUE TITLE
Bots are dumb if automatically spawned by the server and not manually by use through the F12 menu/chat (fun-bots-1.6.0.1)

### ISSUE THREAD

**Issue by zmifsx** [Joe91/fun-bots#28]
This happened since the earlier 1.5 build but I just noticed this behaviour a few days ago. Sometimes you can change all other accuracy stuff/spawn whatever but if you touch the FOV setttings even just decrease by 10 only 2/16 enemy bots will attack you and none at all from friendly faction. The 1.6 build starts at 160 FOV and only a few bots do attack. When changed to 200, it does work again.

**Comment by Joe91** [comment]
As far as I tested this, this works as intended for me. If I narrow the FOV down, the bots of course only see you when you are in front of them. But on my server they still attack each other and me, whenever I'm in the FOV. But maybe I am missing something. Is there a way to reproduce your error, so that I can look at it in detail?

**Comment by SmartShots** [comment]
> This happened since the earlier 1.5 build but I just noticed this behaviour a few days ago. Sometimes you can change all other accuracy stuff/spawn whatever but if you touch the FOV setttings even just decrease by 10 only 2/16 enemy bots will attack you and none at all from friendly faction. The 1.6 build starts at 160 FOV and only a few bots do attack. When changed to 200, it does work again.

I've been testing the MOD since it started and I've been using a lower FOV for most of that time (I like 120) and I have never noticed this. The only difference I can see is that you talk about having 16 BOTs whereas I have mine set to 15 at most. I will test it with 16 BOTs.

As Joe says - with the reduced FOV the BOTs should not attack you if you are behind or to the side of their FOV, the lower the FOV the further round to the front of the BOTs you will have to be for them to 'see' you. Is this what you are talking about?

BOTs from your own team are not supposed to attack you.

**Comment by SmartShots** [comment]
I just tested this with the latest master build with no changes at all to the config, with 16 BOTs on the enemy team, and for me all of the BOTs are attacking me as expected. (Ouch!)

With 8 BOTs on each team all of the BOTs are 100% attacking the opposing teams BOTs.

All tests were done on the Noshahr Canals TDM map.

I have now re-done the tests with the FOV reduced to 150 in the Config.lua file. Results were the same, all appears to be working fine. I cannot reproduce your issue.

I would suggest that you re-test making sure you have the latest build then if you still get the issue post again letting me know and attach your Config.lua so I can check it for myself.

**Comment by zmifsx** [comment]
![Uploading Battlefield 3 - Venice Unleashed [Beta Build 17487] 17_2_2021 11_06_44 PM.png…]()

**Comment by zmifsx** [comment]
Result if default fov 160 on fun-bots-1.6.0.1 (60hz server) 16 enemy vs 15 friendly
Only 2 bots or none at all shoot, the rest just walk past by each other.
No settings changed at all

Result if 200 fov on fun-bots-1.6.0.1 ((60hz server) 16 enemy vs 15 friendly
All bots are active
Touched only FOV settings by changing the fov and kicking all the bots then re-add them. 

Could it be any conflict or errors from other mods?

**Comment by zmifsx** [comment]
Result if default fov 160 on fun-bots-1.6.0.1 (60hz server) 16 enemy vs 15 friendly
Only 2 bots or none at all shoot, the rest just walk past by each other.
No settings changed at all

Result if 200 fov on fun-bots-1.6.0.1 ((60hz server) 16 enemy vs 15 friendly
All bots are active
Touched only FOV settings by changing the fov and kicking all the bots then re-add them. 

Could it be any conflict or errors from other mods?

**Comment by zmifsx** [comment]
The FOV settings have no connection at all. This problem only happens if you add bots without kicking the default 5 added by the spawn mode set in the config. One thing that I also noticed is that the bots that you spawn first vs later are more intelligent than the latter.

**Comment by SmartShots** [comment]
I have just done some more testing. I haven't noticed any difference in the 'intelligence' of the automatically spawned BOTs and the manually spawned BOTs. I think you may be seeing a general difference in BOT behaviour sometimes, which has nothing to do with when or how they are spawned. The BOTs just appear more intelligent sometimes than they do at other times.

Again I cannot reproduce your issue.

**Comment by zmifsx** [comment]
Default 5 + 11 spawned enemy + 15 spawned friendly
![Battlefield 3 - Venice Unleashed  Beta Build 17487  17_2_2021 11_04_50 PM](https://user-images.githubusercontent.com/58888818/108284744-c3f1df00-71c0-11eb-9f6c-1990bd602e2f.png)

Manually spawned bots
![Battlefield 3 - Venice Unleashed  Beta Build 17487  17_2_2021 11_06_44 PM](https://user-images.githubusercontent.com/58888818/108284814-e5eb6180-71c0-11eb-9297-54f8d13c4d14.png)

As you all can't seem to reproduce the issue, should I be closing it?

**Comment by SmartShots** [comment]
I'm not sure what the screenshots have to do with what you are reporting here?

You have stated you raised this issue regarding the BOTs being less intelligent when they are spawned automatically rather than manually? I think, although I'm not really clear on that either because you said above "This problem only happens if you add bots without kicking the default 5 added by the spawn mode set in the config. One thing that I also noticed is that the bots that you spawn first vs later are more intelligent than the latter." but then you changed the issue title to "Bots are dumb if automatically spawned by the server and not manually by use through the F12 menu/chat" which is the opposite of what you said above?

I don't see how those screenshots are related to the issue you have reported here? It doesn't show anything that would indicate some of the BOTs behaving more or less intelligently. It looks like the screenshots are actually relevant for issue #34 that I have reported though. I noticed whilst testing for this issue that sometimes the BOTs were not attacking one another, which these screenshots seem to show as well.

As to whether you should close this issue - that's up to you but if you want it looking into then we need you to clarify what it is exactly you are reporting because it is not clear at all.

**Comment by Joe91** [comment]
What setup for spawning did you use? The increment with players?

**Comment by zmifsx** [comment]
> I'm not sure what the screenshots have to do with what you are reporting here?
> 
> You have stated you raised this issue regarding the BOTs being less intelligent when they are spawned automatically rather than manually? I think, although I'm not really clear on that either because you said above "This problem only happens if you add bots without kicking the default 5 added by the spawn mode set in the config. One thing that I also noticed is that the bots that you spawn first vs later are more intelligent than the latter." but then you changed the issue title to "Bots are dumb if automatically spawned by the server and not manually by use through the F12 menu/chat" which is the opposite of what you said above?
> 
> I don't see how those screenshots are related to the issue you have reported here? It doesn't show anything that would indicate some of the BOTs behaving more or less intelligently. It looks like the screenshots are actually relevant for issue #34 that I have reported though. I noticed whilst testing for this issue that sometimes the BOTs were not attacking one another, which these screenshots seem to show as well.
> 
> As to whether you should close this issue - that's up to you but if you want it looking into then we need you to clarify what it is exactly you are reporting because it is not clear at all.

I'm really sorry for the inconvenience. I changed the title etc because I just figured out what actually caused it.

The flow is like this:

If bots are spawned by the server and you add more bots to fill the team (any team)
then the bots won't attack at all just walk around the traces and thus caused the first screenshot of only 2 bots **to only attack the player**

If you kicked all bots before you add them, everything will be okay as in the second screenshot, every bot works fine.

@SmartShots Your problem said sometimes, mine if you don't kick them, all bots don't work hence the first scoreboard screenshot.

**Comment by zmifsx** [comment]
> What setup for spawning did you use? The increment with players? Does this happen only with this mode, or is it also happening with fixed_number or other modes?
> And do they not attack each other, or also not the player?

It happened to me with all spawning mode. It works ok as long as I set 0 to spawn mode and then manually spawn the bots. Otherwise, the problem occurs again.

All the bots that are affected do not attack other bots and also players. The bots that can attack only attack players as in the first screenshot I posted.

**Comment by zmifsx** [comment]
Do you mind if I record the video of my configuration and gameplay?

**Comment by Joe91** [comment]
I think I found something. Would you mind to try out the new master?

**Comment by zmifsx** [comment]
> I think I found something. Would you mind to try out the new master?
Yes, thank you.

**Comment by Joe91** [comment]
If it still happens: Do you spawn the bots with or without a player on the server?

**Comment by zmifsx** [comment]
> If it still happens: Do you spawn the bots with or without a player on the server?
It will still happen if I set the spawn mode to spawn without a player. If I set to spawn with player it works ok!

**Comment by Joe91** [comment]
Great! Then I think I will remove the spawn without players completely. This was a debug-feature and has no advantage at all in my point of view. Are you okay with this solution?

**Comment by zmifsx** [comment]
Yes, that'd do it. Thank you.

**Comment by Joe91** [comment]
Tere were still some problems. I think in Version 1.6.1.3 they should be solved now...
