### ISSUE TITLE
Mod itself unknowningly corrupted my .map file

### ISSUE THREAD

**Issue by koopa990** [Joe91/fun-bots#320]
### Scope

Core

### What happened?

I was fixing some paths on RUBBLE. I did remember to hit Save before I restart the map, and wouldn't you know --- the mod deleted all traces!!

### What was expected?

...

### How can we reproduce and test it?

This happens randomly and at rare moments. There is no distinctive method to reproduce.

### Version of fun-bots and VU?

2.8.0 release

### I have checked the following... (if applicable)

- [X] I have read the [contribution guidelines on reporting bugs](https://github.com/Joe91/fun-bots/blob/master/.github/CONTRIBUTING.md#reporting-a-bug) and the [code of conduct](https://github.com/Joe91/fun-bots/blob/master/.github/CODE_OF_CONDUCT.md).
- [x] I have tested and reproduced this bug without any other mods besides fun-bots.

**Comment by Joe91** [comment]
Really sorry to hear that!
There is no real mechanism to handle interrupted save progresses. Even if this won't help for now at all:
Just export your files from the database (also while running the game) from time to time. This is the only way you can make sure to have the full controll over the file itself (the exported .map file). Since saving can take some time always make sure to wait till the messsage appears that the save was successfull.
If you export your files then (and maybe also copy them somewhere else or rename them) you can always go back to the last state.
Best of luck!
Joe
