### ISSUE TITLE
Crash when changing maps

### ISSUE THREAD

**Issue by zmifsx** [Joe91/fun-bots#33]
At the end of the match, after the countdown timer goes to 0, the client will load for a while and then the load will fail. Turns out the server crashed.

**Comment by zmifsx** [comment]
Crash ID: d7177b77-1e71-4070-9623-eca701656af6
Build Number: 17487
Release Branch: prod

Dump file
[c5f7180c-3c40-44a2-94e3-45c79187be33.zip](https://github.com/Joe91/fun-bots/files/5996727/c5f7180c-3c40-44a2-94e3-45c79187be33.zip)

**Comment by Bizarrus** [comment]
Dont provide Dump-Files for privacy. Here are sensible informations about you.

You need only the Crash-ID - But we cant check, what errors appears. You must contact `VU` directly with the Crash-ID to get the specific error. Please take this step.

Your description has too low informations:
 * Did your using some other Mods?
 * Did your using custom game modes?
 * Did your using selfmade traces?
 * Which version are you used?
 * Which maps are you try to load?

**Comment by SmartShots** [comment]
This happens to me too. I haven't managed to narrow it down to a MOD being responsible for it, I have a lot of MODs installed and it rarely happens so it's hard to pinpoint. It may well be nothing to do with any MOD and just an issue with VU itself, it is a Beta after all.

What makes you think this issue is down to the Fun-Bots MOD?

**Comment by zmifsx** [comment]
Yup, other mods caused the server crash.
