### ISSUE TITLE
Assault Bots without defibs will stand ontop of dead teammates trying to revive them

### ISSUE THREAD

**Issue by Simber1** [Joe91/fun-bots#333]
### Scope

General bot behavior

### What happened?

If you have an assault bot who doesn't have defibs equipped they will stand on top of dead teammates spinning around trying to revive them but unable to since they lack defibs

### What was expected?

Not attempt to revive any teammates

### How can we reproduce and test it?

I was using my [Randomiser mod](https://github.com/Simber1/VU-Randomizer) which gives everyone random loadouts on spawn.  

- Have a bot spawn as the assault class but no defibs.
- Die in front of them
- Observe as they rotate on top of you while looking at your body

### Version of fun-bots and VU?

Funbot v2.8.0, VU 20079, [VU-Randomizer](https://github.com/Simber1/VU-Randomizer)

### I have checked the following... (if applicable)

- [X] I have read the [contribution guidelines on reporting bugs](https://github.com/Joe91/fun-bots/blob/master/.github/CONTRIBUTING.md#reporting-a-bug) and the [code of conduct](https://github.com/Joe91/fun-bots/blob/master/.github/CODE_OF_CONDUCT.md).
- [ ] I have tested and reproduced this bug without any other mods besides fun-bots.

**Comment by Joe91** [comment]
I think this mod will cause several other issues with fun-bots, since all the weapon-teaching and stats just might be invalid or wrong. But you can try if the fix I pushed on this branch solves this main-issue for you...
I would strongly reommend to investigate this a little further and maybe just use this mod on real players and not on bots?
Or maybe integrate some parts of it into fun-bots itself?
