### ISSUE TITLE
Suggestion - Separate waypoints/traces data from mod.db

### ISSUE THREAD

**Issue by Defenesesword** [Joe91/fun-bots#49]
Since I know that every setting(maybe include trace data?) is written into mod.db(best thanks  Joe91!)
Example like:
Player record Norshal TDM trace 1 ->Save trace data into %funbotfolder%/traces/MP_018/TDM/trace1.db
Record Norshal TDM CQ trace 2 ->Save trace data into %funbotfolder%/traces/MP_018/TDM_CQ/trace2.db
Record Norshal Conquest trace 3 ->Save trace data into %funbotfolder%/traces/MP_018/Conquest/trace3.db
.../trace15.db(15 traces in total)
I dont know if it is a good idea or not(increase your working time on reconstructing code...),but I think we can share our trace file ,perfect the botroad and reduce your workload😊

**Comment by Joe91** [comment]
All tracedata is in there as well. As far as I know you cannot create a new database wile. But I will check this again.
If someone has new paths, they can just send me the database file and I can merge them together...

**Comment by Defenesesword** [comment]
but when funbots update,new default waypoint will replace my recorded old traces...
btw,sometimes I record trace and let the test bot run,they just stand there do nothing,and this record cannot be saved properly

**Comment by Joe91** [comment]
yeah, therefore you need to copy your mod.db file before, as the database is in the zip-file and therefore overwrites you pahts. With the copy you can merge them together with sql-lite editor.
Right now the save progress is a little compicated because of the new system. You have to do the right things in the right order.
We will try to improve the handling a little and to document the usage...

**Comment by Defenesesword** [comment]
Got it,thanks!
